---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: 'us-east-1'
  tasks:
    - name: Create New Key Pair with specified Keyname
      ec2_key:
        name: sshkeypair
        region: us-east-1
        key_material: 'ssh-rsa AAAAB3NzaC user@rhel7'
        force: false
